#!/bin/bash

set -e

if ! getent group zentyal-mfui > /dev/null 2>&1
then
    addgroup --system zentyal-mfui
fi
if ! getent passwd zentyal-mfui > /dev/null 2>&1
then
    adduser --system --home /var/lib/zentyal-mfui/ \
        --disabled-password --ingroup zentyal-mfui zentyal-mfui
fi

CORNER_LOG="/var/log/zentyal-mfui/"
test -d $CORNER_LOG || mkdir $CORNER_LOG
chown -R zentyal-mfui:zentyal-mfui $CORNER_LOG

# create user session ids and conf directories
test -d /var/lib/zentyal-mfui/conf/ || mkdir -p /var/lib/zentyal-mfui/conf/
test -d /var/lib/zentyal-mfui/sids/ || mkdir -p /var/lib/zentyal-mfui/sids/
chown -R zentyal-mfui:zentyal-mfui /var/lib/zentyal-mfui

# Setup random redis password
REDIS_PASS="/var/lib/zentyal-mfui/conf/redis.passwd"
if [ ! -f $REDIS_PASS ]; then
   touch $REDIS_PASS
   chmod 0660 $REDIS_PASS
   tr -dc A-Za-z0-9 < /dev/urandom | head -c10 > $REDIS_PASS
fi
chown zentyal-mfui:ebox $REDIS_PASS

# create zentyal mfui apache certificates
/usr/share/zentyal/create-certificate /var/lib/zentyal-mfui/ssl > /dev/null 2>&1 || true

